import '../styles/layout.scss';

import Header from '../components/header';
import React from 'react';

export const metadata = {
    title: 'BeatAnalytics',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <html lang='en'>
                <body>
                    <Header />
                    <main>{children}</main>
                    {/* footer */}
                </body>
            </html>
        </>
    );
}
